name: CI

on:
  push:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test-environment-job:
    name: Deploy to test
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        shell: bash
        run: echo "Test environment something run"
        
  stage-environment-job:
    name: Deploy to stage
    runs-on: ubuntu-latest
    environment: test
    needs:
      - test-environment-job
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        shell: bash
        run: echo "Stage environment something run"
